
package view;

import javax.swing.table.DefaultTableModel;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.UIManager;
import java.sql.*;
import java.util.Vector;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.basic.BasicListUI;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import pack1.DBConnect;

public class QuanLyNhanVien extends javax.swing.JPanel {

    String tk;
    final String header[] = {"Ma Nhan Vien", "Ten Nhan Vien", "Ngay Thue"};
    final DefaultTableModel tb = new DefaultTableModel(header, 0);
    
    DBConnect cn = new DBConnect();
    Connection conn;
    
    public QuanLyNhanVien(String tk) {
        this.tk=tk;
        initComponents();
        loadBang();
    }
    
    public void xoaTrang() {
        txtma_nhan_vien.setText("");
        txtten_nhan_vien.setText("");
        txtngay_thue.setText("");
        loadBang();
        txtma_nhan_vien.setEnabled(true);
    }
    
    public void loadBang() {
        try {
            conn = cn.getConnection();
            int number;
            Vector row;
            String sql = "select ma_nhan_vien,ten_nhan_vien,ngay_thue from nhan_vien where kho_quan_ly='" + tk +"'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            ResultSetMetaData metadata = rs.getMetaData();
            number = metadata.getColumnCount();
            tb.setRowCount(0);
            while (rs.next()) {
                row = new Vector();
                for (int i = 1; i <= number; i++) {
                    row.addElement(rs.getString(i));
                }
                tb.addRow(row);
                dgvNhanVien.setModel(tb);
            }

            st.close();
            rs.close();
            conn.close();

        } catch (Exception e) {
            System.out.println(e.toString());
        }

        dgvNhanVien.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (dgvNhanVien.getSelectedRow() >= 0) {
                    txtma_nhan_vien.setText(dgvNhanVien.getValueAt(dgvNhanVien.getSelectedRow(), 0) + "");
                    txtten_nhan_vien.setText(dgvNhanVien.getValueAt(dgvNhanVien.getSelectedRow(), 1) + "");
                    txtngay_thue.setText(dgvNhanVien.getValueAt(dgvNhanVien.getSelectedRow(), 2) + "");
                    txtma_nhan_vien.setEditable(false);
                }
            }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtngay_thue = new javax.swing.JTextField();
        txtten_nhan_vien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ThemBut = new javax.swing.JButton();
        SuaBut = new javax.swing.JButton();
        XoaBut = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dgvNhanVien = new javax.swing.JTable();
        txtma_nhan_vien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(246, 246, 174));

        txtngay_thue.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        txtten_nhan_vien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel1.setText("Mã Nhân Viên");

        jLabel2.setText("Ngày Thuê");

        jLabel3.setText("Tên Nhân Viên");

        ThemBut.setBackground(new java.awt.Color(25, 174, 144));
        ThemBut.setForeground(new java.awt.Color(255, 255, 255));
        ThemBut.setText("Thêm");
        ThemBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemButActionPerformed(evt);
            }
        });

        SuaBut.setBackground(new java.awt.Color(25, 174, 144));
        SuaBut.setForeground(new java.awt.Color(255, 255, 255));
        SuaBut.setText("Sửa");
        SuaBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaButActionPerformed(evt);
            }
        });

        XoaBut.setBackground(new java.awt.Color(25, 174, 144));
        XoaBut.setForeground(new java.awt.Color(255, 255, 255));
        XoaBut.setText("Xóa");
        XoaBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaButActionPerformed(evt);
            }
        });

        dgvNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        dgvNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        dgvNhanVien.setRowHeight(30);
        jScrollPane2.setViewportView(dgvNhanVien);

        txtma_nhan_vien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-group.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/machine-repair.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/garbage.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/schedule (1).png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id-card.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/name.png"))); // NOI18N

        btnHuy.setBackground(new java.awt.Color(25, 174, 144));
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtma_nhan_vien, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(txtten_nhan_vien))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addGap(192, 192, 192))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnHuy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ThemBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SuaBut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(XoaBut))
                            .addComponent(txtngay_thue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6)
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtngay_thue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(txtma_nhan_vien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtten_nhan_vien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemBut)
                    .addComponent(SuaBut)
                    .addComponent(XoaBut)
                    .addComponent(btnHuy))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SuaButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaButActionPerformed
        // TODO add your handling code here:
        // Code Sua du lieu
        conn = cn.getConnection();
        try {
            if (txtten_nhan_vien.getText().equals("") || txtngay_thue.getText().equals("") ) {
                JOptionPane.showMessageDialog(this, "BanCanNhapDuDULieu");// Loi~ thieu du lieu khi nhap
            } else {
                Statement st = conn.createStatement();
                String a = txtten_nhan_vien.getText();
                String formattedA = formatFirstLetterUppercase(a);
                String sql = "update nhan_vien set ten_nhan_vien = N'" + formattedA + "', ngay_thue = '" + txtngay_thue.getText()
                        + "' where ma_nhan_vien ='" + txtma_nhan_vien.getText() + "'and kho_quan_ly ='" +tk +"'";
                st = conn.createStatement();
                int kq = st.executeUpdate(sql);
                if (kq > 0) {
                    JOptionPane.showMessageDialog(this, "SuaThanhCong");
                    xoaTrang();
                }
                st.close();
            }
            conn.close();
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_SuaButActionPerformed

    private void ThemButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemButActionPerformed
        // TODO add your handling code here:
        
        conn = cn.getConnection();
        try {
            if(txtma_nhan_vien.getText().equals("") || txtten_nhan_vien.getText().equals("") ||txtngay_thue.getText().equals("")){
                JOptionPane.showMessageDialog(this, "BanCanNhapDuLieu");
            }
            else{
                StringBuffer sb = new StringBuffer();
                String sql_check_pk = "select ma_nhan_vien from nhan_vien where ma_nhan_vien= '" + txtma_nhan_vien.getText() + "'and kho_quan_ly ='"+tk+"'";
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(sql_check_pk);
                if (rs.next()) {
                    sb.append("Ma Nhan Vien Da Ton Tai");
                }
                if (sb.length() > 0) {
                    JOptionPane.showMessageDialog(this, sb.toString());

                } else {
                    String a = txtten_nhan_vien.getText();
                    String formattedA = formatFirstLetterUppercase(a);

                    String sql = "insert into nhan_vien values('" + txtma_nhan_vien.getText() + "',N'"
                            + formattedA + "','" + txtngay_thue.getText() + "','"
                            + tk + "')";
                    st = conn.createStatement();
                    int kq = st.executeUpdate(sql);
                    if (kq > 0) {
                        JOptionPane.showMessageDialog(this, "ThemMoiThanhCong");
                        xoaTrang();
                    }
                    rs.close();
                }
                st.close();
            }
            conn.close();
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_ThemButActionPerformed

    private void XoaButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaButActionPerformed
        // TODO add your handling code here:
        // Code xoa du lieu
        conn = cn.getConnection();
        try {
            String sql = "delete nhan_vien where ma_nhan_vien ='" + txtma_nhan_vien.getText() + "'";
            Statement st = conn.createStatement();
            int chk = JOptionPane.showConfirmDialog(this, "Ban Chac Chan Muon Xoa Chu", "ThongBao!",JOptionPane.YES_NO_OPTION);            
            if (chk == JOptionPane.YES_OPTION) {
                st.execute(sql);
                JOptionPane.showMessageDialog(this, "Xoa Thanh Cong!");
                xoaTrang();
            } 
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_XoaButActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        txtma_nhan_vien.setText("");
        txtten_nhan_vien.setText("");
        txtngay_thue.setText("");
        txtma_nhan_vien.setEditable(true);
    }//GEN-LAST:event_btnHuyActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SuaBut;
    private javax.swing.JButton ThemBut;
    private javax.swing.JButton XoaBut;
    private javax.swing.JButton btnHuy;
    private javax.swing.JTable dgvNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtma_nhan_vien;
    private javax.swing.JTextField txtngay_thue;
    private javax.swing.JTextField txtten_nhan_vien;
    // End of variables declaration//GEN-END:variables

    private String formatFirstLetterUppercase(String input) {
        if (input == null || input.isEmpty()) {
        return input;
    }

    String[] words = input.split("\\s+");
    StringBuilder formattedText = new StringBuilder();

    for (String word : words) {
        if (word.length() > 0) {
            String firstLetter = word.substring(0, 1).toUpperCase();
            String remainingLetters = word.substring(1).toLowerCase();
            formattedText.append(firstLetter).append(remainingLetters).append(" ");
        }
    }

    return formattedText.toString().trim();
    }

}
