/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import pack1.*;
import javax.swing.table.DefaultTableModel;
import pack1.DBConnect;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.Connection;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Windows 10 Pro
 */
public class ThemHang extends javax.swing.JPanel {
    public String tk;
    DBConnect db = new DBConnect();
    Connection conn;
    /**
     * Creates new form ThemHang
     */
    public ThemHang(String tk) {
        this.tk=tk;
        initComponents();
        LocalDate today = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = today.format(formatter);
        txt_ngaylap.setText(formattedDate);
    }
    
    public void reset(){
        DefaultTableModel tableModel = (DefaultTableModel) TableThemHang.getModel();
        tableModel.setRowCount(0);
        tableModel.setRowCount(22);
        TableThemHang.setModel(tableModel);
        txt_donhang.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableThemHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_donhang = new javax.swing.JTextArea();
        btnXacnhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_ngaylap = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(246, 246, 174));

        TableThemHang.setAutoCreateRowSorter(true);
        TableThemHang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TableThemHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hàng", "Tên hàng", "Đơn giá ", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableThemHang.setColumnSelectionAllowed(true);
        TableThemHang.setRowHeight(30);
        TableThemHang.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TableThemHangPropertyChange(evt);
            }
        });
        TableThemHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TableThemHangKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TableThemHang);
        TableThemHang.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (TableThemHang.getColumnModel().getColumnCount() > 0) {
            TableThemHang.getColumnModel().getColumn(0).setMinWidth(250);
            TableThemHang.getColumnModel().getColumn(0).setMaxWidth(250);
            TableThemHang.getColumnModel().getColumn(1).setMinWidth(500);
            TableThemHang.getColumnModel().getColumn(1).setMaxWidth(500);
            TableThemHang.getColumnModel().getColumn(2).setMinWidth(250);
            TableThemHang.getColumnModel().getColumn(2).setMaxWidth(250);
            TableThemHang.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mã đơn hàng: ");

        txt_donhang.setColumns(1);
        txt_donhang.setRows(1);
        jScrollPane2.setViewportView(txt_donhang);

        btnXacnhan.setText("Xác nhận");
        btnXacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacnhanActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel2.setText("Ngày nhập hàng:");

        txt_ngaylap.setEditable(false);
        txt_ngaylap.setColumns(1);
        txt_ngaylap.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_ngaylap.setRows(1);
        jScrollPane3.setViewportView(txt_ngaylap);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 125, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacnhanActionPerformed
        // TODO add your handling code here:
        boolean trangthai=true;
        HangTable hangtable = new HangTable();
        conn = db.getConnection();
        int i=0,number;
        String Mahoadon = txt_donhang.getText();
        
        Statement st = null;
        ResultSet rs = null;
        String sql;
        try{
            LocalDate today = LocalDate.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String formattedDate = today.format(formatter);
            while(TableThemHang.getValueAt(i, 0)!=null){ //|| TableThemHang.getValueAt(i, 0).toString().isEmpty()){ //Ktra bảng đầy đủ thông tin chưa
                Object a1 = TableThemHang.getValueAt(i, 0);
                Object a2 = TableThemHang.getValueAt(i, 1);
                Object a3 = TableThemHang.getValueAt(i, 2);
                Object a4 = TableThemHang.getValueAt(i, 3);
                if(a1==null||a2==null||a3==null||a4==null){
                    throw new e("Bạn cần nhập đủ dữ liệu");
                }
                i++;
            }
            if(Mahoadon == null || "".equals(Mahoadon)){
                throw new e ("Vui lòng nhập mã hóa đơn !");
            }
            if(i==0){
                throw new e ("Không được để hóa đơn rỗng !");
            }
            int rowCount = i;   // lấy dl ở bảng
            int columnCount = TableThemHang.getColumnCount();
            for (int row = 0; row < rowCount; row++) {
               String a = (String) TableThemHang.getValueAt(row, 0);
               String b = (String) TableThemHang.getValueAt(row, 1);
               long c = (long) TableThemHang.getValueAt(row, 2);
               int d = (int) TableThemHang.getValueAt(row, 3);
               if(c<0){
                   throw new e("Đơn giá không thể âm");
               }
               if(d<0){
                   throw new e("Số lượng không thể âm");
               }
               HangDb hang = new HangDb(a,b,c,d);
               hangtable.AddItem(hang);
            }
            hangtable.setNgaylap(formattedDate);
            hangtable.setMahoadon(Mahoadon);
            hangtable.Tinhtonggt();
            
            // Thêm đơn hàng 
            sql = "select maHoaDon from HoaDon where maKho= '" + tk + "' and maHoaDon ='" +hangtable.getMahoadon() +"'" ;
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            //Kiểm tra hóa đơn đã có
            if(rs.next()){
                throw new e("Mã đơn hàng đã tồn tại. Vui lòng thử lại !");
            }

            for(i=0;i<hangtable.GetSoLuong();i++){ // kiểm tra hàng - hàng đã có và chưa có
                sql = "select MaHang,TenHang,DonGia,SoLuong from Hang where maKho = '"+tk +"' and MaHang = '" + hangtable.GetItem(i).getMaHang() + "' and TenHang =N'" + hangtable.GetItem(i).getTenHang() + "' and DonGia = " + hangtable.GetItem(i).getDonGia();
                st = conn.createStatement();
                rs = st.executeQuery(sql);
                if(!rs.next()){
                    sql = "select MaHang from Hang where maKho= '" + tk + "' and MaHang = '" + hangtable.GetItem(i).getMaHang() +"'" ;
                    st = conn.createStatement();
                    rs = st.executeQuery(sql);
                    if(rs.next()){
                        throw new e ("Sai thông tin mặt hàng! vui lòng thử lại");
                    }
                } 
            }
            
            for(i=0;i<hangtable.GetSoLuong();i++){ // thêm hàng 2 th - hàng đã có và chưa có
                sql = "select MaHang,TenHang,DonGia,SoLuong from Hang where maKho = '"+tk +"' and MaHang = '" + hangtable.GetItem(i).getMaHang() + "' and TenHang =N'" + hangtable.GetItem(i).getTenHang() + "' and DonGia = " + hangtable.GetItem(i).getDonGia();
                st = conn.createStatement();
                rs = st.executeQuery(sql);
                if(rs.next()){
                    number = rs.getInt(4);
                    number = number + hangtable.GetItem(i).getSoLuong();
                    sql = "Update Hang set soLuong = " + number + "where maHang = '" + hangtable.GetItem(i).getMaHang() +"'" ;
                    st = conn.createStatement();
                    int kq = st.executeUpdate(sql);
                }
                else{
                    sql = "insert into Hang values('" + hangtable.GetItem(i).getMaHang() + "',N'"+ hangtable.GetItem(i).getTenHang() + "','" + hangtable.GetItem(i).getDonGia() + "','" +hangtable.GetItem(i).getSoLuong() + "','" + tk + "')";
                    st = conn.createStatement();
                    st.executeUpdate(sql);
                }
                
            }
            //thêm hóa đơn
            sql = "insert into HoaDon values('" + hangtable.getMahoadon() + "','"+ hangtable.getTonggiatri() + "','" + hangtable.getNgaylap() + "','"+ tk + "',N'Nhập','ADMIN')";
            st = conn.createStatement();
            int kq = st.executeUpdate(sql);
            //Thêm các dòng trên hóa đơn đó
            for(i=0;i<hangtable.GetSoLuong();i++){
                sql = "insert into dongHoaDon values('" + hangtable.getMahoadon() + "','"
                        + i+1 + "','" + hangtable.GetItem(i).getMaHang() + "',N'" 
                        +hangtable.GetItem(i).getTenHang() + "','" 
                        +hangtable.GetItem(i).getSoLuong() + "','"
                        +hangtable.GetItem(i).getDonGia() + "','"
                        +hangtable.GetItem(i).getSoLuong() * hangtable.GetItem(i).getDonGia() +"','" + tk +"')";
                st = conn.createStatement();
                st.executeUpdate(sql);
            }
            
            
           
            st.close();
            rs.close();
            conn.close();
            if(trangthai==true){
                JOptionPane.showMessageDialog(this,"Thêm hàng thành công!");
                reset();
            
        
        }
        } catch (SQLException ex) {
            Logger.getLogger(ThemHang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (e e){
            JOptionPane.showMessageDialog(this,e.GetMassage());
        }
               
    }//GEN-LAST:event_btnXacnhanActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void TableThemHangPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TableThemHangPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TableThemHangPropertyChange

    private void TableThemHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableThemHangKeyReleased
        // TODO add your handling code here:
        conn = db.getConnection();
        Statement st = null;
        ResultSet rs = null;
        String sql,ten;
        long dongia;
        int i=0;
        try{
            i=TableThemHang.getSelectedRow();
            
            /*while(TableThemHang.getValueAt(i, 0)!=null){ //|| TableThemHang.getValueAt(i, 0).toString().isEmpty()){ //Ktra bảng đầy đủ thông tin chưa
                    Object a1 = TableThemHang.getValueAt(i, 0);
                    Object a2 = TableThemHang.getValueAt(i, 1);
                    if(a2==null){
                        break;
                    }
                    i++;
                }*/
            int rowCount = i;   // lấy dl ở dòng đang gõ
            String a = (String) TableThemHang.getValueAt(i, 0);
            sql = "select TenHang,DonGia from Hang where maKho = '"+tk +"' and MaHang = '" + a + "'" ;
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            if(rs.next()){
                ten = rs.getString(1);
                dongia = rs.getLong(2);
                TableThemHang.setValueAt(ten, i, 1);
                TableThemHang.setValueAt(dongia, i, 2);
            }
            
        }catch(SQLException ex){
            ex.printStackTrace();
        }
                
               
            
        
    }//GEN-LAST:event_TableThemHangKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableThemHang;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacnhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txt_donhang;
    private javax.swing.JTextArea txt_ngaylap;
    // End of variables declaration//GEN-END:variables
}

